### ISSUE TITLE
Wrong DETAILS for s6-linux-init

### ISSUE THREAD

**Issue by firasuke** [florin65/zlocal#1]
Hey there, I was examining the `s6` init files and I noticed that the `DETAILS` files of `s6-linux-init` was using information from `s6-linux-utils`:

https://github.com/florin65/zlocal/blob/master/init/s6/s6-linux-init/DETAILS

Thanks for your time.

**Comment by florin65** [comment]
Thank you for the notification. The s6 based init is in a WIP stage anyway and I didn't tried it yet. 
It still lacks some needed scripts for most of it's modules.
